version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    volumes:
      - clickhouse_vol:/var/lib/clickhouse
      - ./ddl/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    ports:
      - "9000:9000"
      - "8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_network
  tabix:
    image: spoonest/clickhouse-tabix-web-client
    ports:
        - "8124:80"
    networks:
        - ch_network
    depends_on:
        - clickhouse
    restart: always
networks:
  ch_network:
volumes:
  clickhouse_vol: